# Generated by Django 4.2.4 on 2023-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobduration_joblisting_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
