# Generated by Django 4.2.4 on 2023-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='icon',
            field=models.CharField(default='fa-book-reader', max_length=50, null=True),
        ),
    ]
