# Generated by Django 4.2.4 on 2023-08-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
