# Generated by Django 4.2.4 on 2023-08-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_joblisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='vacancy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
