# Generated by Django 4.2.4 on 2023-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_joblisting_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='loaction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='vacancy',
            field=models.CharField(default='London', max_length=100),
            preserve_default=False,
        ),
    ]
