# Generated by Django 4.2.4 on 2023-08-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_joblisting_loaction_alter_joblisting_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='loaction',
            new_name='location',
        ),
    ]
