# Generated by Django 4.2.4 on 2023-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_rename_loaction_joblisting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='sample@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='sample', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
