# Generated by Django 4.2.4 on 2023-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_application_email_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
